# Generated by Django 4.1.3 on 2022-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startApt', models.CharField(max_length=3)),
                ('endApt', models.CharField(max_length=3)),
            ],
        ),
    ]
