CREATE TABLE IF NOT EXISTS airports (
    'Facility Type' str,
    'ID' str,
    'State' str,
    'County' str,	
    'City' str,
    'Name' str,
    'Ownership' str,	
    'Use' str,	
    'ARP Latitude' float,	
    'ARP Latitude Sec' float,	
    'ARP Longitude' float,	
    'ARP Longitude Sec' float,	
    'Elevation' str,	
    'Magnetic Variation' str,	
    'Sectional' str,
    'Tie In FSS Id' str,
    'Tie In FSS Name' str,
    'FSS Toll Free Number' str,
    'Fuel Types' str,	
    'ATCT' str,	
    'UNICOM' str,	
    'CTAF' str,	
    'ICAO Id' str, 
)